#!/bin/bash

# Auto-Build Environment Setup for PanicStop Command
# Generated by Planner Agent

set -e

echo "========================================"
echo "TradeTerminal Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Project root
PROJECT_ROOT="/Users/bimawa/Developing/Projects/TradeTerminal"
cd "$PROJECT_ROOT"

# Check for required tools
check_tool() {
    if ! command -v "$1" &> /dev/null; then
        echo -e "${RED}$1 is not installed${NC}"
        exit 1
    fi
}

echo "Checking required tools..."
check_tool cargo
check_tool just
echo -e "${GREEN}All tools available${NC}"

# Load environment variables
if [ -f .env ]; then
    echo "Loading .env file..."
    export $(cat .env | grep -v '^#' | xargs)
    echo -e "${GREEN}Environment loaded${NC}"
else
    echo -e "${YELLOW}Warning: .env file not found${NC}"
fi

# Build project
echo ""
echo "Building project..."
cargo build
if [ $? -eq 0 ]; then
    echo -e "${GREEN}Build successful${NC}"
else
    echo -e "${RED}Build failed${NC}"
    exit 1
fi

# Run tests
echo ""
echo "Running tests..."
cargo test
if [ $? -eq 0 ]; then
    echo -e "${GREEN}All tests passed${NC}"
else
    echo -e "${YELLOW}Some tests failed${NC}"
fi

# ============================================
# START SERVICES (Optional)
# ============================================

echo ""
echo "========================================"
echo "To start services manually:"
echo "========================================"
echo ""
echo "  Terminal 1 (Server):"
echo "    cd $PROJECT_ROOT && just server"
echo ""
echo "  Terminal 2 (Client):"
echo "    cd $PROJECT_ROOT && just client"
echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Server WebSocket: ws://127.0.0.1:9000"
echo "  Client: Terminal TUI application"
echo ""
echo "Commands to test:"
echo "  :ps 5           - Panic stop after 5 sec inactivity"
echo "  :ps 3 95000     - Panic stop with trigger price"
echo "  :br 1 0.3% | ps 2 - Pipe chain with panic stop"
echo ""
